"ZZY's vim configuration

set nocompatible
filetype off

set rtp+=D:/Vim/bundle/Vundle.vim/
call vundle#begin('D:/Vim/bundle/')

Plugin 'VundleVim/Vundle.vim'
Plugin 'Valloric/YouCompleteMe'
Plugin 'scrooloose/nerdtree'

call vundle#end()
filetype plugin indent on

source $VIMRUNTIME/vimrc_example.vim
source $VIMRUNTIME/mswin.vim
behave mswin

"set guifont=宋体:h12,Georgia:h12
set encoding=utf-8
set fileencoding=utf-8
set fileencodings=utf-8,gb18030,gbk,gb2312,cp936,ucs-bom
set termencoding=utf-8

set diffexpr=MyDiff()
function MyDiff()
  let opt = '-a --binary '
  if &diffopt =~ 'icase' | let opt = opt . '-i ' | endif
  if &diffopt =~ 'iwhite' | let opt = opt . '-b ' | endif
  let arg1 = v:fname_in
  if arg1 =~ ' ' | let arg1 = '"' . arg1 . '"' | endif
  let arg2 = v:fname_new
  if arg2 =~ ' ' | let arg2 = '"' . arg2 . '"' | endif
  let arg3 = v:fname_out
  if arg3 =~ ' ' | let arg3 = '"' . arg3 . '"' | endif
  let eq = ''
  if $VIMRUNTIME =~ ' '
    if &sh =~ '\<cmd'
      let cmd = '""' . $VIMRUNTIME . '\diff"'
      let eq = '"'
    else
      let cmd = substitute($VIMRUNTIME, ' ', '" ', '') . '\diff"'
    endif
  else
    let cmd = $VIMRUNTIME . '\diff'
  endif
  silent execute '!' . cmd . ' ' . opt . arg1 . ' ' . arg2 . ' > ' . arg3 . eq
endfunction

"语法高亮
syntax on
"自动检测文件类型并加载相应的设置
filetype plugin indent on

colorscheme evening
set number
set nowrap

"自动缩进
set autoindent
"自动缩进格式
set cindent
"智能对齐方式
set smartindent

set expandtab
set smarttab

"制表符宽度
set tabstop=4
set softtabstop=4
"缩进空格数
set shiftwidth=4

"缺省不产生的文件
set nobackup
set noundofile
set noswapfile

"NERDTree config
"vim启动自动打开NERDTree
autocmd vimenter * NERDTree
"NERDTree启动后默认光标位置在文件中
autocmd vimenter * wincmd p
"NERDTree调出和隐藏快捷键
map <C-n> :NERDTreeToggle<CR>

"Toggle Menu and Toolbar
""完全隐藏菜单
set guioptions-=m
"完全隐藏工具栏
set guioptions-=T
map <silent> <F2> :if &guioptions =~# 'T' <Bar>
        \set guioptions-=T <Bar>
        \set guioptions-=m <bar>
    \else <Bar>
        \set guioptions+=T <Bar>
        \set guioptions+=m <Bar>
    \endif<CR>






